### ISSUE TITLE
Fast online query for up-to-dateness

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#103]
Currently it takes way too long (about 30s+ for game, engine and lobby) to check (through the `--download-*` commands) whether the version we have matches the latest version online.

This should be doable in a very short amount of time (approximately one server query per resource), although this may require some data format redesign (not familiar with how its currently setup).

**Comment by abma** [comment]
this was heavily improved:

in most cases only http://repos.springrts.com/repos.gz
and http://reponame.springrts.com/versions.gz will be downloaded

for further speed-ups -> https://github.com/springfiles/upq/issues/25
