### ISSUE TITLE
Update Spring submodule

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#107]
Can we apply update Spring's submodule with current master?
I would like to use https://github.com/spring/pr-downloader/commit/5638cd651d23a45cfb952c325d53f0c1e86f541a (or rather, the binaries that are created in that way).

However, I can't confirm that this works well, so I'm asking you instead. I had some issues with it in previous testing, and had to invoke `DownloadShutdown` and `DownloadInit` [after each download](https://github.com/Spring-Chobby/spring-launcher/blob/master/glfw3/src/spring_downloader.cpp#L56-L61), but this could be a PEBKAC on my side.
I'd like to use the executable version as I still haven't given up on creating a Python launcher -> I think it's just a better idea in general.

**Comment by abma** [comment]
> . I had some issues with it in previous testing, and had to invoke DownloadShutdown and DownloadInit after each download, but this could be a PEBKAC on my side.

what was the issue?

the current changes are not tested very well...

**Comment by gajop** [comment]
The issue was that only the first game would be downloaded, all consequent game downloads would not work. So if you had one game, one map and one engine, it would be OK, but if you had 2+ games, only the first game would get downloaded. 
You can see the workaround code there as well as the entire download module, and maybe I am using it wrong (but I don't think so..).

**Comment by gajop** [comment]
Well hokomoko has updated it for better or for worse, so closing this issue.
