### ISSUE TITLE
Pr Downloader Fails

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/pr-downloader#114]
http://logs.springrts.com/logfiles/65/
I updated evo and it's working pretty well on 1208. I have the alpha test host using that engine version and this is what happened when I ran the launcher and joined it. So, it might be a version thing, not sure.

Specifically the map and engine and game all failed to dl
lines
41
51
60
264

fwiw I did try removing cacert just in case, but no dice.

Let me know if more info needed.

**Comment by silentwings** [comment]
seem its


  | [2019-05-02 02:16:06.320] [warn] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:87:DownloadUrl():Error in curl Unsupported protocol (Protocol https not supported or disabled in libcurl) [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:207:search():Error downloading https://api.springfiles.com/json.php?category=map&torrent=true&springname=Living Lands 4.1  [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:87:DownloadUrl():Error in curl Unsupported protocol (Protocol https not supported or disabled in libcurl) [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:207:search():Error downloading https://api.springfiles.com/json.php?category=map&torrent=true&springname=FolsomDamDeluxeV4
-- | --

**Comment by silentwings** [comment]
also

[2019-05-02 02:14:18.391] [info] Download started: 104.0.1-968-gb54c668 maintenance, engine, --filesystem-writepath,C:\Users\Forboding Angel\AppData\Roaming\Evolution RTS,--download-engine,104.0.1-968-gb54c668 maintenance

perhaps later engines already contained a fix?

**Comment by abma** [comment]
yep, older pr-downloader windows builds don't support https correctly. see #112
