### ISSUE TITLE
add byar-chobby to rapid?

### ISSUE THREAD

**Issue by Ruwetuin** [spring/pr-downloader#115]
Add the following repo to rapid so chobby can try load gameconfig modules instead of offer all gameconfigs itself.

https://github.com/beyond-all-reason/BYAR-Chobby

**Comment by abma** [comment]
please fix case-sensitive modinfo.lua

https://github.com/spring/RapidTools/issues/56

**Comment by abma** [comment]
erro, forget it, everything fine, its to hot here :-|

**Comment by abma** [comment]
done!

kudos go to @gajop

**Comment by abma** [comment]
please note
https://github.com/spring/pr-downloader/issues/117
