### ISSUE TITLE
Please add EvolutionRTS/EvoRTS-Chobby to rapid (mutator for Evo specific chobby settings)

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/pr-downloader#116]
https://github.com/EvolutionRTS/EvoRTS-Chobby/

Thank you <3

**Comment by abma** [comment]
please fix case-sensitive modinfo.lua

https://github.com/spring/RapidTools/issues/56

**Comment by abma** [comment]
erro, forget it, everything fine

**Comment by abma** [comment]
fixed!

kudos go to @gajip! thanks!

also please note
https://github.com/spring/pr-downloader/issues/117
