### ISSUE TITLE
it cannot find map but does generate a junk .sd7

### ISSUE THREAD

**Issue by Ruwetuin** [spring/pr-downloader#122]
gajop:
i also cannot find the map here: https://api.springfiles.com/files//lava_highground.sd7
[2020-03-08 03:10:36.282] [warn] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:460:processMessages():CURL error(1:22): HTTP response code said error 404 (https://api.springfiles.com/files//lava_highground.sd7)

i think that's junk
seems like prd proceeds with a download despite not actually finding it...
if you just want to play probably getting it from here is a good idea: https://springfiles.com/spring/spring-maps/lava-highground-0

**Comment by abma** [comment]
path was wrong, try again please, the links returned both now work:

https://api.springfiles.com/?filename=lava_highground.sd7

**Comment by gajop** [comment]
The real problem is https://github.com/Spring-Chobby/Chobby/files/4302278/spring-launcher.log (line 1033 and later).
Even after getting a 404, pr-downloader (engine integration) tries to download it, receives invalid pieces and reports download success

**Comment by abma** [comment]
@gajop:
where can i report bugs about spring launcher? the repo is.. sneaky.

**Comment by gajop** [comment]
@abma https://github.com/gajop/spring-launcher
