### ISSUE TITLE
SSL cert issues

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#127]
http://logs.springrts.com/logfiles/581/

**Comment by abma** [comment]
not sure what this is, but this needs some more verbose error:

very likely the tls trust store on the user is to old / doesn't contain a valid chain for repos.springrts.com

**Comment by abma** [comment]
relevant error message:

  | [2020-11-05 10:09:09.853] [warn] [Error] ../../tools/pr-downloader/src/Downloader/Rapid/RapidDownloader.cpp:203:ParseFD():Broken /home/israel/Documentos/Beyond All Reason/rapid/repos.springrts.com/repos.gz: 0
-- | --
31 | [2020-11-05 10:09:09.962] [warn] [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:87:DownloadUrl():Error in curl Problem with the SSL CA cert (path? access rights?) (error setting certificate verify locations:   CAfile: /etc/ssl/certs/ca-certificates.crt   CApath: /etc/ssl/certs) [Error] ../../tools/pr-downloader/src/Downloader/Http/HttpDownloader.cpp:207:search():Error downloading https://api.springfiles.com/json.php?category=game&torrent=true&springname=byar:test  [Error] ../../tools/pr-downloader/src/main.cpp:195:main():No game found for byar:test [Error] ../../tools/pr-downloader/src/main.cpp:240:main():Error occurred while downloading: 1

**Comment by abma** [comment]
needs to be tested again: works for me, so i expect an issue with the installed "ca-certificates" package.
