### ISSUE TITLE
UX issue: launching partially-updated games

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#129]
When the rapid registry gets updated, but game isn't fully downloaded, trying to launch the game without finishing the update will fail as the tagged version won't exist.

Launcher should either be prevented to start or it should start using the previous rapid version (which would require us to a keep a history of rapid tags, e.g. history of byar:test, chobby:test, etc.)

**Comment by gajop** [comment]
Not sure why I keep creating issues in the wrong repo. sigh

**Comment by abma** [comment]
thats a sign for vacation needed! :-)
