### ISSUE TITLE
Couldn't resolve host name 0 (https://repos.springrts.com/repos.gz)

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#131]
https://github.com/gajop/spring-launcher/issues/71

**Comment by abma** [comment]
network issue: i don't see what pr-downloader could do without net.

**Comment by abma** [comment]
recently springrts.com sadly is overloaded, so a lot of errors come from this i guess.

only questionable is: should pr-downloader retry or is that something the chobby should do?
