### ISSUE TITLE
broken .sdp file

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#135]
https://github.com/gajop/spring-launcher/issues/62

**Comment by abma** [comment]
double linking sucks, copy and pasted from the refered issue:

http://logs.springrts.com/logfiles/584/
http://logs.springrts.com/logfiles/602/
http://logs.springrts.com/logfiles/532/

**Comment by abma** [comment]
needs to be testet with the more verbose prd and see if it happens again.

i guess something is locking the file.
