### ISSUE TITLE
Failed to open pool archive .gz file (broken/invalid file?)

### ISSUE THREAD

**Issue by gajop** [spring/pr-downloader#137]
https://github.com/gajop/spring-launcher/issues/51

**Comment by abma** [comment]
http://logs.springrts.com/logfiles/576/
http://logs.springrts.com/logfiles/575/
http://logs.springrts.com/logfiles/561/

**Comment by abma** [comment]
needs to be testet with the more verbose prd and see if it happens again.

i guess something is locking the file.
