### ISSUE TITLE
Rapid building broken after deploy yesterday.

### ISSUE THREAD

**Issue by p2004a** [spring/pr-downloader#149]
See: https://repos.springrts.com/byar/log.txt 

```
(...)
git_libgit2_init() [1]
(...)
```

I suggest applying https://github.com/beyond-all-reason/pr-downloader/commit/91424a84a29a5a820cfdb8f8aff6a2508a745288 to fix the issue. The api changed a bunch of years ago when the libgit2 was updated, see documentation for that function: https://libgit2.org/libgit2/#HEAD/group/libgit2/git_libgit2_init

PS: Another fix we have in BAR fork for rapid tools is https://github.com/beyond-all-reason/pr-downloader/commit/5730d6e96041324635d84cc6c4a229a366e4a089

**Comment by abma** [comment]
thank you!

https://github.com/spring/pr-downloader/commit/810aa91a63e1ff6451a233eddd2cce29238482d1
