### ISSUE TITLE
Unregister byar from repos.springrts.com

### ISSUE THREAD

**Issue by p2004a** [spring/pr-downloader#152]
Beyond All Reason is no longer using the repos.springrts.com hosting but we are using our own since over 2 years now. Providing byar at repos.springrts.com can be confusing:
- It's not hosting the exact same list of versions
- At the moment the repo byar at repos.springrts.com is hosting corrupted version of the game: it's missing a set of files, to be exact, it's missing:

```
64b89dd05b4bf4685583b93d8d05741a: sounds/voice/en/allison/battleended.wav
70e693dca4945ec5b075f0a1e9e0a19f: sounds/voice/en/allison/lavadropping.wav
cd06264c82151e6c83686858e83c77d2: sounds/voice/en/allison/lavarising.wav
23178cb254ab503d8d94099f408f0d52: sounds/voice/en/allison/teamdownlastcommander.wav
64d89aaedbfa63eaa61a7d73209768c6: sounds/voice/en/razkharn/battleended.wav
2cb81a761682d4c64f7e696bc99186f5: sounds/voice/en/razkharn/lavadropping.wav
c1888640b9facc30046dcfd8bce6d2f7: sounds/voice/en/razkharn/lavarising.wav
55972dd48ca68f99eb0622c411c90028: sounds/voice/en/razkharn/teamdownlastcommander.wav
9d24e6d27b26ee7b51f7d102add3fda9: sounds/voice/en/winter/lavadropping.wav
0d9114d4795ebd782e2c1f41ba703953: sounds/voice/en/winter/lavarising.wav
```

so I would also recommend verifying if some other repos at repos.springrts.com aren't also hosting corrupted packages at the moment.

**Comment by Beherith** [comment]
Indeed, we have moved off of springfiles completely, and are grateful for your hosting so far. Please remove BAR (byar) from repos.springrts.com, as outdated fallback options are causing issues on our side. 

@abma Thank you!

**Comment by abma** [comment]
done
