### ISSUE TITLE
CFile::Open tries to open files when it should create new one

### ISSUE THREAD

**Issue by Usaga** [spring/pr-downloader#91]
When I was fixing bug with non-ascii chars prevented pr-downloader from downloading files, I found that when download was aborted for some reason, next try for download the same files will fail due CFile::Open will not try to overwrite files that remained since last time. I found there some code that will try to open those files with "rb+" mode and try to change it's size... I do not know the meaning of that behaviour. 

May be this should be changed to always rewrite opened files because this method is alway used for creating new files for writing?

This happens on Windows.

**Comment by abma** [comment]
this is used for restart a (partial) download.

what does fail?

**Comment by abma** [comment]
sorry, i don't see why this should be changed. rewriting existing files will break resuming of downloads.
