### ISSUE TITLE
Latest versions of PR-Downloader sending too much ACK info?

### ISSUE THREAD

**Issue by ForbodingAngel** [spring/pr-downloader#94]
The cause is a shot in the dark based upon pure speculation. SWL always downloads the latest version of PR-Downloader every time the lobby starts up. This is generally a good thing, however, lately, downloading in the lobby causes it to become nearly unresponsive (the dl keeps going but the lobby ui locks up) while downloading. Ikinz speculated that perhaps pr downloader is sending so much progress information that the lobby is being overwhelmed.

Is this intentional? Is it a bug? Is it something the lobby needs to handle better?

**Comment by abma** [comment]
you should report this to SWL, i have no clue what you mean / it sounds unrelated to pr-downloader.

**Comment by ForbodingAngel** [comment]
Okies, thanks :-)
