### ISSUE TITLE
Sometimes a download completes instantly even though VFS thinks the resource is missing

### ISSUE THREAD

**Issue by GoogleFrog** [spring/pr-downloader#95]

**Comment by db81** [comment]
Does it still assume a .sdp is downloaded properly if it exists, even if the file is actually empty?

**Comment by abma** [comment]
log output / infolog.txt would be nice in such a case

**Comment by abma** [comment]
https://github.com/spring/pr-downloader/blob/master/src/Downloader/Rapid/Sdp.cpp#L79

yes: it downloads the file to a temp filename and when its done it renames it. pr-downloader assumes that a rename is atomic, so the file should be never 0 bytes.

which version of pr-downloader is used? this "feature" isn't this new. afaik weblobby used a long time an old version of pr-downloader which hadn't this feature enabled.

https://github.com/spring/pr-downloader/blob/master/src/Downloader/Rapid/Sdp.cpp#L70
