### ISSUE TITLE
Missing Compile Instructions

### ISSUE THREAD

**Issue by tomjn** [spring/pr-downloader#98]
The readme links to the spring engine wiki, but that only contains usage instructions.

Instead, build instructions would be better off in this repo so that a network connection isn't required, nor a spring wiki login

**Comment by gajop** [comment]
fwiw you don't need a login to read the spring wiki

**Comment by tomjn** [comment]
no but you do need a login to change things on it, and it doesn't help that it's lacking instructions

I've ran this locally:

```
cmake .
make
```

Which appears to have generated make files and built the tests as `.app` bundles which was surprising. Thankfully the tests pass if I run:

```
> test/prd_test.app/Contents/MacOS/prd_test
Running 1 test case...

*** No errors detected
```

It did create a dylib and a cli command `pr-downloader` in the `src` folder, I was expecting a build or dist folder

```
~/dev/git/pr-downloader/src git::master 
❯ ./pr-downloader
pr-downloader 0.7-385-g286ede6
Usage: ./pr-downloader 
--rapid-download <name>
--rapid-validate
--delete
--dump-sdp <name>
--validate-sdp <name>
--http-download <name>
--http-search <name>
--download-map <name>
--download-game <name>
--download-engine <name>
--filesystem-writepath <name>
--disable-logging
--help
--version
```

**Comment by abma** [comment]
https://springrts.com/wiki/Pr-downloader#compile

**Comment by gajop** [comment]
There's still no information about what external dependencies are required. Reopening.

**Comment by abma** [comment]
https://github.com/spring/pr-downloader/blob/master/.travis.yml#L11

**Comment by gajop** [comment]
I see. Still, let's write it down since it's not super clear even from that.
For example, I think `libjsoncpp-dev` is optional, and exists locally, no?

**Comment by abma** [comment]
https://springrts.com/wiki/Pr-downloader#install_depencies_on_debian
